name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write # This is required for requesting the JWT

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps chromium
      - name: Test vitests
        run: pnpm test -- run --coverage --coverage.reporter=clover
      - name: Code coverage upload
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/clover.xml
          use_oidc: true
      - name: Build docs
        run: pnpm run docs
      - name: Test stories
        run: |
          # Run the preview server in the background
          pnpm preview &
          sleep 3
          pnpm playwright test stories/snapshot.spec.ts
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results
          path: test-results
          if-no-files-found: ignore